name: MSA
subtitle: 2018
permalink: none
//baseurl: /msabuild/
relurl: ../

delay_3: "-webkit-animation-delay: .333s; -moz-animation-delay: .333s; -ms-animation-delay: 
.333s; animation-delay: .333s;"
delay_6: "-webkit-animation-delay: .666s; -moz-animation-delay: .666s; -ms-animation-delay: 
.666s; animation-delay: .666s;"
delay1: "-webkit-animation-delay: 1s; -moz-animation-delay: 1s; -ms-animation-delay: 
1s; animation-delay: 1s;"
delay1_3: "-webkit-animation-delay: 1.333s; -moz-animation-delay: 1.333s; -ms-animation-delay: 
1.333s; animation-delay: 1.333s;"
delay1_6: "-webkit-animation-delay: 1.666s; -moz-animation-delay: 1.666s; -ms-animation-delay: 
1.666s; animation-delay: 1.666s;"
delay2: "-webkit-animation-delay: 2s; -moz-animation-delay: 2s; -ms-animation-delay: 
2s; animation-delay: 2s;"
delay2_3: "-webkit-animation-delay: 2.333s; -moz-animation-delay: 2.333s; -ms-animation-delay: 
2.333s; animation-delay: 2.333s;"

delay1_5: "-webkit-animation-delay: 1.5s; -moz-animation-delay: 1.5s; -ms-animation-delay: 
1.5s; animation-delay: 1.5s;"
delay2: "-webkit-animation-delay: 1.9s; -moz-animation-delay: 2s; -ms-animation-delay: 
2s; animation-delay: 2s;"
delay2_5: "-webkit-animation-delay: 2.3s; -moz-animation-delay: 2.5s; -ms-animation-delay: 
2.5s; animation-delay: 2.5s;"
delay3: "-webkit-animation-delay: 2.7s; -moz-animation-delay: 3s; -ms-animation-delay: 
3s; animation-delay: 3s;"
delay3_5: "-webkit-animation-delay: 3.1s; -moz-animation-delay: 3.5s; -ms-animation-delay: 
3.5s; animation-delay: 3.5s;"
delay4: "-webkit-animation-delay: 3.5s; -moz-animation-delay: 4s; -ms-animation-delay: 
4s; animation-delay: 4s;"
delay4_5: "-webkit-animation-delay: 3.9s; -moz-animation-delay: 4.5s; -ms-animation-delay: 
4.5s; animation-delay: 4.5s;"
delay5: "-webkit-animation-delay: 4.1s; -moz-animation-delay: 5s; -ms-animation-delay: 
5s; animation-delay: 5s;"

modernist_redvolution: rgb(210,35,42);
hamlindigo_blue: rgb(87,82,180); 